build(yarn2/gulp/eleventy): add missing dep?
```
yarn build
[18:19:57] Using gulpfile ~/dev/github/eleventy-playground/eleventy-classic-blog-starter/gulpfile.js
[18:19:57] Starting 'build'...
[18:19:57] Starting 'clean'...
[18:19:57] Finished 'clean' after 46 ms
[18:19:57] Starting 'justCopy'...
[18:19:57] Starting 'buildCSS'...
[18:19:57] Finished 'buildCSS' after 173 ms
[18:19:57] Starting 'buildHTML'...
[18:19:57] Finished 'justCopy' after 200 ms
Eleventy fatal error: (more in DEBUG output)
> Error in your Eleventy config file '/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.eleventy.js'.

`EleventyConfigError` was thrown
> Your application tried to access nunjucks, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: nunjucks (via "nunjucks")
Required by: /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/

Require stack:
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.eleventy.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateConfig.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/Config.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateEngineManager.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/EleventyExtensionMap.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateRender.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateData.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/Eleventy.js
- /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/cmd.js

`Error` was thrown:
    Error: Your application tried to access nunjucks, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

    Required package: nunjucks (via "nunjucks")
    Required by: /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/

    Require stack:
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.eleventy.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateConfig.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/Config.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateEngineManager.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/EleventyExtensionMap.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateRender.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateData.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/Eleventy.js
    - /Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/cmd.js
        at internalTools_makeError (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.pnp.js:15057:34)
        at resolveToUnqualified (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.pnp.js:16010:23)
        at resolveRequest (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.pnp.js:16108:29)
        at Object.resolveRequest (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.pnp.js:16186:26)
        at Function.external_module_.Module._resolveFilename (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.pnp.js:15290:34)
        at Function.external_module_.Module._load (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.pnp.js:15155:48)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at module.exports (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.eleventy.js:43:20)
        at TemplateConfig.mergeConfig (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/@11ty-eleventy-npm-0.11.1-919d4911b1-b536835de5.zip/node_modules/@11ty/eleventy/src/TemplateConfig.js:91:25)
[18:19:58] 'buildHTML' errored after 752 ms
[18:19:58] Error: exited with error code: 1
    at ChildProcess.onexit (/Users/pc/dev/github/eleventy-playground/eleventy-classic-blog-starter/.yarn/cache/end-of-stream-npm-1.4.4-497fc6dee1-7da60e458b.zip/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:548:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    at Process.callbackTrampoline (internal/async_hooks.js:129:14)
[18:19:58] 'build' errored after 984 ms
```